### PR TITLE
Add support for cover entities

### PR DESCRIPTION
**Pull request by nijel**
This allows opening the gate in addition to unlocking the door.

### CODE REVIEW

**Comment by AngellusMortis** [comment]
Oh, I meant to reply on this, but you can make a follow up PR if you want to do it. 

I might recommend linking the lock and cover actions to each other. So, the one action does both if they are both provided? The notification actions are basically designed to only allow a single action, so that means if you provide a lock and cover, you cannot do them both at once. It is one or the other based on which you tap first.

**Comment by nijel** [comment]
I thought that both lock and gate might be present, so it's better to have both actions separate (I actually have a door and gate, but the door lock is not electric, so it cannot be controlled). But if you prefer to merge them, I can look at it again.

**Comment by AngellusMortis** [comment]
If they are both present, it is not possible to do them both in a single notification. The notification only allows you to respond once.

**Comment by nijel** [comment]
I think it's okay to do a single action - for example, when somebody walks in, I want to open the door lock, when somebody drives with a car, I would like to open the gate.

**Pull request merged**
